version: "3"

services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
